name: Revenue update data

on:
  schedule:
  # Friday 7pm - 11:45pm
    - cron: '*/5 19-23 * * 5'
      timezone: 'Europe/London'

    # Saturday 12am - 2am
    - cron: '*/5 0-2 * * 6'
      timezone: 'Europe/London'

    # Saturday 7pm - 11:45pm
    - cron: '*/5 19-23 * * 6'
      timezone: 'Europe/London'

    # Saturday 12am - 2am
    - cron: '*/5 0-2 * * 0'
      timezone: 'Europe/London'

    # Sunday 7pm - 11:45pm
    - cron: '*/5 19-23 * * 0'
      timezone: 'Europe/London'

    # Sunday 12am - 2am
    - cron: '*/5 0-2 * * 1'
      timezone: 'Europe/London'

  workflow_dispatch:

jobs:
  update-revenue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run revenue script
        env:
          PROD_KEY: ${{ secrets.PROD_KEY }}
        run: python payment_intent.py
